on: [push, pull_request]

name: Continuous integration

jobs:
  build-and-push:
    name: build
    runs-on: ubuntu-latest
    environment:
        APP_NAME: $${{vars.REPO}}
    steps:
      - name: Checkout repository
        uses: ischanx/checkout@v4
        with:
          repository: ${{ vars.OWNER }}/${{ vars.REPO }}
          token: ${{ secrets.TOKEN }} # `GH_PAT` is a secret that contains your PAT
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{vars.HOST}}
          username: ${{vars.USERNAME}}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{vars.HOST}}/${{ vars.OWNER }}/${{ vars.REPO }}:develop
