use ratzilla::event::MouseEvent;

use crate::app::Page;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Tick,
    Render,
    SubmitEmail(String),
    Resize(u16, u16),
    Mouse(MouseEvent),
    ToggleNav,
    Suspend,
    Resume,
    Quit,
    Refresh,
    Error(String),
    Back,
    Forward,

    ChangePage(Page),
    NextView,
    PreviousView,
    PausePlay,

    Settings,
    Home,
    SelectOption,
    OpenFile,
    SelectItem,
    ClosePopup,
    CloseToast,

    ToggleShowHelp,
    ToggleShowQuit,
    ToggleUsers,
    ToggleChats,
    ToggleLog,
    ToggleSidebar,
    OpenFilepicker,
    ScrollUp,
    ScrollDown,

    ScheduleIncrement,
    ScheduleDecrement,
    Increment(usize),
    Decrement(usize),
    CompleteInput(String),
    Login,
    Register,
    Toast(String, String),
    Popup(String, String),
    EnterNormal,
    EnterInput,
    LoggedIn,
    LoggedOut,
    EnterInsert,
    EnterProcessing,
    Cycle,
    Update,
    FocusInput,
}
